name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'IanComradeBot'
    permissions:
      contents: read
      pull-requests: write
      issues: write        # SD-Fix test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:                # ADT Tweak by Schrodinger
        sync-labels: true  # Поправил auto-labels
